name: 1.0.$(BuildId)

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    PackageVersion: $(Build.BuildNumber)
  ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
    PackageVersion: $(Build.BuildNumber)-$(Build.SourceBranchName)

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- bash: ./build.sh --target Init
  displayName: 'helm init'
- bash: ./build.sh --target Update
  displayName: 'helm update'
- bash: ./build.sh --target Lint
  displayName: 'helm lint'
- bash: ./build.sh --target Package --PackageVersion=$(PackageVersion)
  displayName: 'helm package'
- task: AzureCLI@1
  displayName: 'az acr helm push'
  inputs:
    azureSubscription: 'Azure'
    scriptLocation: scriptPath
    scriptPath: ./build.sh
    arguments: --target Push --verbosity Diagnostic --AzureContainerRegistryName='$(AzureContainerRegistryName)' --AzureContainerRegistryUsername='$(AzureContainerRegistryUsername)' --AzureContainerRegistryPassword='$(AzureContainerRegistryPassword1)'
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'HelmCharts'
    targetPath: './Artefacts'