name: 1.0.$(BuildId)-$(SourceBranchName)

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- bash: ./build.sh --target Lint
  displayName: 'helm lint'
- bash: ./build.sh --target Package
  displayName: 'helm package'
- task: AzureCLI@1
  displayName: 'az acr helm push'
  inputs:
    azureSubscription: 'Azure'
    scriptLocation: scriptPath
    scriptPath: ./build.sh
    arguments: --target Push --verbosity Diagnostic --AzureContainerRegistryName='$(AzureContainerRegistryName)' --AzureContainerRegistryUsername='$(AzureContainerRegistryUsername)' --AzureContainerRegistryPassword='$(AzureContainerRegistryPassword1)'