# Azure Pipelines documentation https://aka.ms/yaml

name: 1.0.$(BuildId)

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    PackageVersion: $(Build.BuildNumber)
  ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
    PackageVersion: $(Build.BuildNumber)-$(Build.SourceBranchName)

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: HelmInstaller@1
  displayName: Install Helm
  inputs:
    helmVersionToInstall: latest
- bash: dotnet tool install --global Cake.Tool
  displayName: 'install cake global tool'
- bash: dotnet cake --target=Init
  displayName: 'helm init'
- bash: dotnet cake --target=Update
  displayName: 'helm update'
- bash: dotnet cake --target=Lint
  displayName: 'helm lint'
- bash: dotnet cake --target=Package --PackageVersion=$(PackageVersion)
  displayName: 'helm package'
- task: AzureCLI@1
  displayName: 'az acr helm push'
  inputs:
    azureSubscription: 'Azure'
    scriptLocation: inlineScript
    inlineScript: 'dotnet cake --target=Push --verbosity=Diagnostic --AzureContainerRegistryName="$(AzureContainerRegistryName)" --AzureContainerRegistryUsername="$(AzureContainerRegistryUsername)" --AzureContainerRegistryPassword="$(AzureContainerRegistryPassword1)"'
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'HelmCharts'
    targetPath: './Artefacts'
