name: 1.0.$(BuildId)

pool:
  vmImage: 'Ubuntu 16.04'
#-$(SourceBranchName)
steps:
- bash: echo '##vso[task.setvariable variable=Version;isOutput=true]$(Build.BuildNumber)'
  condition: eq(variables['Build.SourceBranchName'], 'master')
- bash: echo '##vso[task.setvariable variable=Version;isOutput=true]-$(Build.SourceBranchName)'
  condition: ne(variables['Build.SourceBranchName'], 'master')

- bash: ./build.sh --target Init
  displayName: 'helm init'
- bash: ./build.sh --target Update
  displayName: 'helm update'
- bash: ./build.sh --target Lint
  displayName: 'helm lint'
- bash: ./build.sh --target Package
  displayName: 'helm package'
- task: AzureCLI@1
  displayName: 'az acr helm push'
  inputs:
    azureSubscription: 'Azure'
    scriptLocation: scriptPath
    scriptPath: ./build.sh
    arguments: --target Push --verbosity Diagnostic --AzureContainerRegistryName='$(AzureContainerRegistryName)' --AzureContainerRegistryUsername='$(AzureContainerRegistryUsername)' --AzureContainerRegistryPassword='$(AzureContainerRegistryPassword1)'