# Azure Pipelines documentation https://aka.ms/yaml

name: 1.0.$(BuildId)

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    PackageVersion: $(Build.BuildNumber)
  ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
    PackageVersion: $(Build.BuildNumber)-$(Build.SourceBranchName)

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  lfs: true
- task: HelmInstaller@1
  displayName: 'Install Helm'
  inputs:
    helmVersionToInstall: latest
- script: 'dotnet tool install --global Cake.Tool'
  displayName: 'Install cake global tool'
  failOnStderr: true
- script: 'dotnet cake --target=Init'
  displayName: 'Helm Init'
  failOnStderr: true
- script: 'dotnet cake --target=Update'
  displayName: 'Helm Update'
  failOnStderr: true
- script: 'dotnet cake --target=Lint'
  displayName: 'Helm Lint'
  failOnStderr: true
- script: 'dotnet cake --target=Package --PackageVersion=$(PackageVersion)'
  displayName: 'Helm Package'
  failOnStderr: true
- task: AzureCLI@1
  displayName: 'Azure Container Registry Push'
  inputs:
    azureSubscription: 'Azure'
    scriptLocation: inlineScript
    inlineScript: 'dotnet cake --target=Push --verbosity=Diagnostic --AzureContainerRegistryName="$(AzureContainerRegistryName)" --AzureContainerRegistryUsername="$(AzureContainerRegistryUsername)" --AzureContainerRegistryPassword="$(AzureContainerRegistryPassword1)"'
- publish: './Artifacts'
  artifact: 'HelmCharts'
  displayName: 'Publish Artifacts'
