resourceQuota:
  cpu: 10
  memory: "20Gi"
  persistentvolumeclaims: 0
  pods: 10
  services:
    loadbalancers: 5
    nodeports: 0

environment: "Production"

home:
  replicaCount: 1
  image:
    repository: nginx
    tag: stable
  service:
    type: LoadBalancer
    port: 80
  priorityClassName: "high"
  rollingUpdate:
    maxSurge: "25%" # Maximum number of pods to create during an update (Default=25%)
    maxUnavailable: "25%" # Maximum number of pods to take down during a rolling update (Default=25%)
  podDisruptionBudget:
    minAvailable: null
    maxUnavailable: "1%"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

kured:
  nameOverride: ""
  fullnameOverride: ""
  image.pullPolicy: Always
  resources:
    limits:
      cpu: 10m
      memory: 10Mi
    requests:
      cpu: 10m
      memory: 10Mi

# redis-ha:
#   nameOverride: "redis"
#   replicas: 2
#   auth: false
#   # redisPassword: '' TODO
#   persistentVolume:
#     enabled: false